apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # change the name of the PVC if creating a new one
  name: volume-{change-name}
spec:
  storageClassName: rook-cephfs-tide 
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      # change storage amount if creating a new PVC
      storage: 250Gi